### ISSUE TITLE
Provide a Gatsby Source plugin

### ISSUE THREAD

**Issue by daltonrowe** [spacecloud-io/space-cloud#132]
Gatsby is a popular progressive web app generator providing code-split statically rendered React apps. Providing a source plugin would enable more developers to use their Space Cloud data in conjunction with Gatsby.

This relates to https://github.com/spaceuptech/space-cloud/issues/93

If GraphQL data retrieval is possible Gatsby can consume it with https://www.gatsbyjs.org/packages/gatsby-source-graphql/

**Comment by YourTechBud** [comment]
Hey @daltonrowe. Since we now have a GraphQL api as well. You think you can help us with this feature?

**Comment by YourTechBud** [comment]
New release will support GraphQL introspection
