### ISSUE TITLE
Support where clause operators with underscore in the GraphQL variables 

### ISSUE THREAD

**Issue by HeyItsJs** [spacecloud-io/space-cloud#1377]
### The problem faced currently?

The syntax for comparison operators in the `where` clause is different when specifying them directly in the GraphQL query vs specifying them in the GraphQL variables. In the GraphQL query, we have to specify operators with an underscore (e.g. `_gt`). However, while specifying operators in the variables, we have to use `$` (e.g. `$gt`). 

This creates confusion while switching between the two methods.

### How can we solve it?

Simple. Support both underscore and dollar operators in the GraphQL variables.

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
Added in `v0.22.0`
