### ISSUE TITLE
There are not the document for the  older version

### ISSUE THREAD

**Issue by pandaxxt** [spacecloud-io/space-cloud#1475]
### The problem faced currently?
Currently the document are the newest version, there are not the usage guide for the old version, for example, the aggregation document , https://docs.spaceuptech.com/storage/database/queries/aggregations/ , that is for the 0.20.2, but my version is 0.18.4, there are the difference using for the aggregation function.

### How can we solve it?
Add the use guide for the difference version in the web page.  It is better that the document can be compatible with the old version, and new functions should be added on the basis of the old version

**Comment by YourTechBud** [comment]
We will start versioning from v0.22.0 onwards
