### ISSUE TITLE
Add examples on how to use client SDKs both go & js

### ISSUE THREAD

**Issue by Sharad-Regoti-Unotech** [spacecloud-io/space-cloud#1554]
### The problem faced currently?
Currently, there is no documentation on how to use js & go SDK

### How can we solve it?

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
These sdks are deprecated and no work will continue on them. Version `v0.22.0` will autogenerate seagger apis you can use to generate clients.
