### ISSUE TITLE
Allow joins when using REST API

### ISSUE THREAD

**Issue by kselectride** [spacecloud-io/space-cloud#1557]
### The problem faced currently?
Currently cannot use joins in the REST API, see https://github.com/spaceuptech/space-cloud/blob/master/gateway/server/handlers/crud.go#L168

### How can we solve it?
Allow joins to be used in the REST API

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
To allow this, we will first need to evaluate the security rules of the joint tables.

**Comment by YourTechBud** [comment]
Coming in `v0.21.5`
