### ISSUE TITLE
Architecture Link in Readme 404s

### ISSUE THREAD

**Issue by jpowell** [spacecloud-io/space-cloud#1559]
### Describe the bug

The `Detailed Space Cloud architecture` link in the `How it works` section of the Readme 404s.

**Comment by YourTechBud** [comment]
Oops. Need to get that fixed

**Comment by 10allday** [comment]
> ### Describe the bug
> The `Detailed Space Cloud architecture` link in the `How it works` section of the Readme 404s.

This pull request fixes it. #1565
