### ISSUE TITLE
Cannot perform space-cli destroy (and possibly other actions) because accounts.yaml is missing

### ISSUE THREAD

**Issue by shubham4443** [spacecloud-io/space-cloud#1577]
### Describe the bug
I want to destroy space-cloud cluster but I'm getting an error while doing so
```
PS D:\Shubham Files\spaceuptech\space-cli> space-cli destroy
? Space cloud cluster with id (space-cloud-a000a7ba-24ca-4be9-bbc3-838db116f1f6) will be destoryed, Do you want to continue YesN) y
time="2021-08-20T22:17:28+05:30" level=error msg="error getting credential unable to read accounts config file - open C:\\Users\\Shubham/.space-cloud/accounts.yaml: The system cannot find the file specified."
time="2021-08-20T22:17:28+05:30" level=error msg="Couldn't get account details or login token" error="open C:\\Users\\Shubham/.space-cloud/accounts.yaml: The system cannot find the file specified."
Error: Couldn't get account details or login token
```
The reason could be I don't have accounts.yaml inside my Users/.space-cloud folder. But I have not deleted it by myself.
### Expected behaviour
cluster gets destroyed
### Actual behaviour 
getting error regarding missing accounts.yaml file

### Steps to reproduce
enter space-cli destroy command in the terminal

### Your environment
- Space Cloud version: 0.21.1
- OS: Windows
- Kubernetes or Docker: Kubernetes
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
This can be easily solved by asking the user to proceed with the destroy operation when no config is found.

**Comment by YourTechBud** [comment]
New clinis being built which removes the need of this command completely
