### ISSUE TITLE
Add a confirmation for before deleting the project

### ISSUE THREAD

**Issue by riginoommen** [spacecloud-io/space-cloud#1619]
### The problem faced currently?
There is no confirmation prior to deletion so accidental deletion happens
![image](https://user-images.githubusercontent.com/3840244/177340331-2392fb6a-8edf-4838-9109-1dd7177e14cf.png)

### How can we solve it?
Give a prompt before deleting it

**Comment by YourTechBud** [comment]
The concept of projects will be completely removed in the next release
