### ISSUE TITLE
[Bug] Unable to initialise space cloud when no source for graphql module is provided

### ISSUE THREAD

**Issue by shubham4443** [spacecloud-io/space-cloud#1640]
### Describe the bug

Not able to initialise space-cloud with empty config. For example starting the space-cloud with file adapter having no configs in sc-config folder or with k8s adapter having no resources in the cluster.

### Expected behavior

space-cloud should start with empty config.

### Steps to reproduce

Start spacecloud without any config.

### Your environment
- Space Cloud version: v0.22.0
- OS: Ubuntu
- Kubernetes or Docker: Kubernetes
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
The issue is with the GraphQL provider

**Comment by YourTechBud** [comment]
We should add a custom field for exposing stats about SpaceCloud (for e.g. SC version)

```gql
{
  sc_buildInfo {
    version
  }
}
```

**Comment by prithvi081099** [comment]
Can I do this task?

**Comment by YourTechBud** [comment]
Sure
