### ISSUE TITLE
[Feature] Add support for RSA Secrets

### ISSUE THREAD

**Issue by YourTechBud** [spacecloud-io/space-cloud#1654]
### The problem faced currently?

We only support HSA Secrets. We should support RSA as well.

### How can we solve it?

- Create a new CRD struct in `pks/apis` for RSA
- Create a corresponding source in the `sources/auth` directory

That's it

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by prithvi081099** [comment]
I am taking this issue

**Comment by YourTechBud** [comment]
Awesome
