### ISSUE TITLE
[Feature] Add support for basic package management in spacectl

### ISSUE THREAD

**Issue by shubham4443** [spacecloud-io/space-cloud#1665]
Create additional client generation commands:

- `spacectl client init` - To create sc.yaml config file and required folder structure. Folder structure includes `operation` folder where client stores graphql files and `resources` folder where space-cloud generates `CompiledGraphqlSources` CR.
- `spacectl client sync` - A command which runs continuously in the background. This command watches for file changes in the `operation` folder, computes the CR, apply diff in CR and subscribe for `/sc/apiman/provision` events. It will also populate the `config` field in sc.yaml file as and when graphql files are created/deleted.

**Comment by YourTechBud** [comment]
`spacectl client init`

- Creates an `sc.yaml` file in `.space-cloud` folder
- File contains:
    - Name of workspace (`name`)
    - Labels - Default set of labels to be added to each resource being applied- Make sure we implicitly add a label `space-cloud.io/workspace=<name>`
    - BaseURL of SpaceCloud - Defaults to `http://localhost:4122` (configurable via `--base-url` flag)
    - Output:
        - Client Gen language - E.g. rtk-query
        - Directory of generated files
    - Directory of source files - Defaults `.space-cloud/resources`

`spaceclt client apply -f <dir>`
- Retrieve all CRs from current workspace
- Calculate deltas between resources received from SC vs those present in source directory
- Apply the delta to SpaceCloud.

`spacectl client get all <name>`
- Retrieve all CRs from current workspace
- Print all resources as a table on the screen
