### ISSUE TITLE
[Bug] Does not work with 1.27.7 Kubernetes

### ISSUE THREAD

**Issue by shyim** [spacecloud-io/space-cloud#1708]
### Describe the bug

./space-cli setup
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta2"

### Expected behavior
it works as expected

### Steps to reproduce
Install fresh k3s and then spacecloud

### Your environment
- Space Cloud version: newest
- OS: Debian
- Kubernetes or Docker: Kubernetes
- Browser (if applicable):

**Comment by Zhaobudaoyuema** [comment]
May I ask how you solved the problem? I encountered the same problem

**Comment by dillfrescott** [comment]
Same issue
