### ISSUE TITLE
Use fasthttprouter to improve performance

### ISSUE THREAD

**Issue by HeyItsJs** [spacecloud-io/space-cloud#294]

**Comment by YourTechBud** [comment]
We can probably use [gin](https://github.com/gin-gonic/gin) or [echo](https://github.com/labstack/echo)

**Comment by mkhennoussi** [comment]
What about [fiber](https://github.com/gofiber/fiber) ? 😁

**Comment by YourTechBud** [comment]
That's an interesting library. I really like it. Maybe we can use that.

**Comment by YourTechBud** [comment]
We are moving to caddy which uses net/http. Bot expecting major changes here
