### ISSUE TITLE
User module stops working after custom authentication entries are created

### ISSUE THREAD

**Issue by didair** [spacecloud-io/space-cloud#321]
### Describe the bug
Right now the user modules stops working if there are other objects in the users database without the field `pass`

### Expected behaviour
The user module should skip the entires with no valid `pass` field (Not empty string, not null, not undefined)

### Your environment
- Space Cloud version: 0.10.x

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
@didair This happens in scenarios when a user inserts something in the `users` table / collection from outside the user man module?

**Comment by didair** [comment]
@YourTechBud yes correct, in my case users authenticated with Facebook don't have the field `pass` and it makes the user module fail.

**Comment by YourTechBud** [comment]
User module will be removed in the next release
