### ISSUE TITLE
Introspection of the graphql schema doesn't work

### ISSUE THREAD

**Issue by YourTechBud** [spacecloud-io/space-cloud#434]
### The problem faced currently?
Can't introspect the graphql schema. A lot of tooling doesn't work for this reason.
### How can we solve it?
If we manage to do #433 then this might be possible as well.
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by s-kris** [comment]
Given that #433 is solved in `v0.14 ` any thoughts on this and #567 ?

**Comment by YourTechBud** [comment]
Introspection is a very tricky piece. Since we have implemented GraphQL ourselves, we will have to implement the introspection piece ourselves as well.

Let's try to do this in `v0.16.0`?

**Comment by s-kris** [comment]
Thank you @YourTechBud 
Just a small addition, it'd be nice to have a `flag` to turn this feature on/off.

**Comment by YourTechBud** [comment]
Will be fixed in next release
