### ISSUE TITLE
no suggestions in explorer while writing a query

### ISSUE THREAD

**Issue by s-kris** [spacecloud-io/space-cloud#567]
### Describe the bug
Even after defining the schema for tables, the explorer doesn't suggest the fields while writing a query
### Expected behaviour
Suggestions for schema fields while writing a query in explorer
### Actual behaviour 
No suggestions are displayed
### Steps to reproduce
Add a table with schema and write a query in explorer
### Your environment
- Space Cloud version: v0.13.1 [Deployed from here https://hub.docker.com/r/spaceuptech/space-cloud/ via CapRover]
- OS: Ubuntu 18.04
- The client api version (if applicable):
- Browser (if applicable):

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
Same as #434

**Comment by YourTechBud** [comment]
Will be fixed in next release
