### ISSUE TITLE
Custom-code clause for security rules

### ISSUE THREAD

**Issue by s-kris** [spacecloud-io/space-cloud#604]
Executing a piece of code as a clause for security rules can solve wide ranges of business logic. 
It also reduces the boilerplate code in security rules.

For example, I generate and assign access-tokens to my web scrapers to read/write db. Earlier, I wrote a small express middleware function to do the validation. In current-version of `space-cloud` I I should just use the `webhook` rule to point to my express server. If you give an option to write custom code, then I don't need to go outside of `space-cloud` at all. 

As discussed on discord, it'd be great to have multiple run-times (to execute custom code) for devs to choose a language which they are comfortable in. 

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
We can look at these libraries to include a runtime
- https://github.com/d5/tengo
- https://github.com/robertkrimen/otto

**Comment by s-kris** [comment]
Looks good to start with these two.

**Comment by s-kris** [comment]
Can you provide support to fetch data from a `custom-url` for `value` field ? 
use case: 
```
{
  "rule": "force",
  "field": "orderId",
  "value": "https://api.myserver.com/v1/generateUniqueId"
}
```
p.s: This is similar to the 'webhook' rule you already have. This way, we can use custom modules as well for complex requirements.

**Comment by YourTechBud** [comment]
@s-kris, maybe we should have a `modify` rule which lets you mutate the entire request / response? I guess this deserves its separate issue.

**Comment by s-kris** [comment]
yes, modify as well. But the point is - the value should be able to be fetched from a remote url. This is because even with the custom code block for rules, we can't let custom modules run on sc (as discussed on discord). So, that can generated from a remote server.

**Comment by YourTechBud** [comment]
Support for OPA will be added in the next release. Dropping this.
