### ISSUE TITLE
Maybe we shouldn't validate the token when using the `webhook` rule

### ISSUE THREAD

**Issue by YourTechBud** [spacecloud-io/space-cloud#626]
Currently we validate the token before calling the webhook. Maybe we shouldn't validate the token when using the `webhook` rule. We can leave it to the webhook endpoint to authenticate and authorise the request.

This is beneficial since even requests with a custom token scheme which sc doesn't support will work. The downside is that users will have to validate tokens themselves.

**Comment by s-kris** [comment]
Give a flag whether to verify in sc or not.

**Comment by YourTechBud** [comment]
Fixed in next version
