### ISSUE TITLE
Updating secret should redeploy concerned deployments in Docker

### ISSUE THREAD

**Issue by HeyItsJs** [spacecloud-io/space-cloud#700]
### The problem faced currently?

Currently, if we are using Docker as a target, updating a secret doesn't restart the concerned deployments (deployments that are using the corresponding secret). So we have to reapply the deployment config.  Ideally, applying a secret should automatically reapply the concerned deployments to ensure that all deployments are working with the latest secrets.

### How can we solve it?

As far as I know, Kubernetes does this out of the box. For Docker, we need to internally reapply the configs of all services in update secret that are using that particular secret. This should work for all the endpoints of updating secret:

- set secret
- delete secret
- set secret key
- update rootPath

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
Doxker support has been removed
