### ISSUE TITLE
Should we retrieve values of secrets?

### ISSUE THREAD

**Issue by HeyItsJs** [spacecloud-io/space-cloud#703]
Right now we are hiding all the values of the secrets. 

For example, if a user has created a secret of type environment variable, then retrieving the value of the secret via the config APIs just returns the name of the secret and the keys within the environment variables, but not the values in the environment variables.

This is fair to some extent so that the values of the secrets are not revealed. However, this might cause an inconvenience to the user in case where he is just not sure of what secret value he has applied. In that case, the user will have to reset the secret value just to ensure that he has the right value applied.

What do you think the right approach should be? Is it fair to hide the secret values or should we show them?

**Comment by YourTechBud** [comment]
I think we should show secret values. We can also make this role based with two levels of access
