### ISSUE TITLE
Option for automatically cleaning events_log table

### ISSUE THREAD

**Issue by sharadregoti** [spacecloud-io/space-cloud#782]
### The problem faced currently?
docs specifies how to clear events_log table
by manually running queries
### How can we solve it?
It would be better if user has a option in mission control to such as automatic cleaning
which will clean the failed records weekly or daily basis
>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by YourTechBud** [comment]
We are deprecating this architecture
