### ISSUE TITLE
Add user management endpoints to graphql

### ISSUE THREAD

**Issue by pandaxxt** [spacecloud-io/space-cloud#924]
### How can we solve it?

>If you want this feature to be implemented, give it a thumbs up reaction, so that we can determine which features are important to you.
>👍

**Comment by aresa7796** [comment]
👍 i think this feature is very Important！

**Comment by YourTechBud** [comment]
Just to be clear, authentication and authorisation is already supported for GraphQL. This issue is regarding adding the user management endpoints to the GraphQL layer

**Comment by YourTechBud** [comment]
This module will be removed
