### ISSUE TITLE
Cannot rename primary key of table

### ISSUE THREAD

**Issue by sharadregoti** [spacecloud-io/space-cloud#950]
### Describe the bug
Renaming column which has primary key throws error 
{"error":"pq: constraint \"c_accounts_uid\" of relation \"accounts\" does not exist"}
### Expected behaviour
It should rename the column
### Steps to reproduce
create a column with a primary key. after creating try changing the name of column which has primary key.
### Your environment
- Space Cloud version: v0.17.0
- OS:linux
- The client api version (if applicable):
- Browser (if applicable):firefox

>If this bug restricts your use of space-cloud, give it a thumbs up reaction, so that we can determine which bugs need to be fixed immediately.
>👍

**Comment by YourTechBud** [comment]
Db schema management will be removed
